version: "3.8"
services:
  load_balancer:
    image: nginx
    ports:
      - 9090:9090
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./nginx/my-site.tmpl:/etc/nginx/conf.d/my-site.conf.template
    # environment:
    #   - FLASK_SERVER_ADDR=app
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/my-site.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app1
      - app2
      - app3
  app1:
    build: ./flask
    ports:
      - "8091:80"
    volumes:
      - ./flask:/app
  app2:
    build: ./flask
    ports:
      - "8092:80"
    volumes:
      - ./flask:/app
  app3:
    build: ./flask
    ports:
      - "8093:80"
    volumes:
      - ./flask:/app